### ISSUE TITLE
Various USB Issues on 10.11

### ISSUE THREAD

**Issue by iHedgehog** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#5] opened 2015-10-02 04:53 UTC
Doing installation according the instruction, without HDA patching. Got this:
![screen shot 2015-10-02 at 07 24 12](https://cloud.githubusercontent.com/assets/6762673/10239709/6d98a35e-68da-11e5-999b-941d029984b8.png)

**Comment by theracermaster** [comment] 2015-10-02 21:39
Copy config-generic.plist to config.plist in the repo folder. The HDA injection part renames it, I should probably rename it elsewhere in the script.

**Comment by iHedgehog** [comment] 2015-10-03 03:24
The error persists. The config is renamed, but it seems to late.

**Comment by theracermaster** [comment] 2015-10-03 15:29
I re-checked and saw that it was still causing the error. Please try v1.8.1, it should have fixed the error.

**Comment by iHedgehog** [comment] 2015-10-04 04:18
Here is some error generating SSDT:
![screen shot 2015-10-04 at 06 12 44](https://cloud.githubusercontent.com/assets/6762673/10266403/13f7d84e-6a68-11e5-8e32-96b5daa28ec1.png)

**Comment by theracermaster** [comment] 2015-10-04 14:15
Please try the latest version again, there were some comments added by git which broke the script.

**Comment by iHedgehog** [comment] 2015-10-04 15:05
@theracermaster and several errors more
![screen shot 2015-10-04 at 17 56 03](https://cloud.githubusercontent.com/assets/6762673/10268482/8b79dcbe-6ac2-11e5-8904-80e236835cec.png)

**Comment by theracermaster** [comment] 2015-10-04 15:21
Please try cloning the repo with the `--recursive` argument. This should properly download all of the external files used by the script.

**Comment by iHedgehog** [comment] 2015-10-04 15:45
![screen shot 2015-10-04 at 18 42 32](https://cloud.githubusercontent.com/assets/6762673/10268659/0e3ee3e2-6ac8-11e5-89c9-ae7a9f20cd58.png)

**Comment by theracermaster** [comment] 2015-10-06 02:06
Should be fixed now, try again please.

**Comment by iHedgehog** [comment] 2015-10-06 03:33
![screen shot 2015-10-06 at 06 15 19](https://cloud.githubusercontent.com/assets/6762673/10299530/caed5678-6bf3-11e5-8feb-ed90d0a4ffe4.png)
![screen shot 2015-10-06 at 06 16 32](https://cloud.githubusercontent.com/assets/6762673/10299566/1f1858e2-6bf4-11e5-85f4-208038bae030.png)
![screen shot 2015-10-06 at 06 17 10](https://cloud.githubusercontent.com/assets/6762673/10299569/23ce6f2a-6bf4-11e5-9859-393a5ea7b44b.png)

**Comment by chroniX0** [comment] 2015-10-06 04:42
I had this same issue but fixed it by deleting the ~/Library/ssdtPRGen folder before running this tool. To start from scratch, you can additionally delete AppleHDA898.kext & FVInjector.kext in the /Library/Extensions folder (not S/L/E); the entire EFI folder that contains the clover bootloader (located in the EFI partition on the disk you installed OSX to); and the tool itself (located ~/Gigabyte-GA-Z77X-DSDT-Patch).

Deleting all those prior to running this should work.

**Comment by iHedgehog** [comment] 2015-10-06 05:25
@chroniX0 thank you, it works.
@theracermaster after Clover updates system didn't boot and the reason is that kexts placed in `Other` folder, not in 10.11 folder. I copy kexts and now it works well. I think you should fix it. Thank you.

**Comment by iHedgehog** [comment] 2015-10-06 06:14
@theracermaster one more thing. GA-Z77X_USB.kext and FakePCIID.kext cause black screen and no working USB after sleep. After I removed these, everything seems fine.

**Comment by theracermaster** [comment] 2015-10-06 21:57
@iHedgehog: The kext issue is something I plan on fixing (in Clover source code). IMO, kexts/Other should load first, then version-specific folders.

Also, have you tried with only FakePCIID (removing the port injector), and the other way around? I haven't encountered any issues with USB with the injector (for full port injection) & FakePCIID_XHCIMux installed (for muxing).

**Comment by iHedgehog** [comment] 2015-10-07 03:10
@theracermaster yes, I've tried to boot with one of this kext (I do not remember which one) and USB ports didn't work at all.

**Comment by chroniX0** [comment] 2015-10-07 13:40
@theracermaster I can confirm that for me at least, one of the USB ports does not work after waking from sleep. It seems to be only one in particular on my Z77X-UD5H. The rest are working fine.

![usb](https://cloud.githubusercontent.com/assets/4286389/10338888/16708f36-6cce-11e5-896a-ab2d7e21d721.jpg)

I originally had an external HDD connected to that port, but after waking from sleep would get the error message "Disk Not Ejected Properly" and the drive was no longer being detected until I reboot. I swapped the ext HDD to another port and put my USB microphone in its place and now I'm no longer receiving that error message and the drive is being detected after waking from sleep. But now the microphone does not work after waking.

**Comment by theracermaster** [comment] 2015-10-07 20:25
Can you please post an IOReg before & after sleep (when the USB port breaks) using the port injector?

**Comment by chroniX0** [comment] 2015-10-08 01:37
Sure I took an IOReg before sleeping (when USB port works) and an IOReg after waking from sleep (when USB port breaks). Here it is: https://transfer.sh/zU3Yd/ioreg.zip

**Comment by theracermaster** [comment] 2015-10-09 00:10
Interesting...it seems that anything under PRT4 (injected with the USB port injector) under EH01/PR01 simply disappears after waking up from sleep. Will investigate this further. [Perhaps ESEL/XSEL methods in the DSDT might be the cause](http://www.insanelymac.com/forum/topic/306777-guide-usb-fix-el-capitan-1011/?p=2148854).

**Comment by chroniX0** [comment] 2015-10-09 16:41
Hmm I got it working now. I came across a suggestion to change the xHCI mode in the UEFI settings because USB is handled a little differently in OSX 10.11. 

So I changed the xHCI Mode to "Enabled" instead of "Auto" or even "Smart Auto". Seems to be working now even after waking from sleep.

Here's an IOReg dump from before and after sleep in case it helps: https://transfer.sh/mcQB7/ioreg.zip

**Comment by theracermaster** [comment] 2015-10-10 00:21
Thanks for the info! I will edit the wiki. Does Smart Auto & Enabled work, or just Enabled?

**Comment by chroniX0** [comment] 2015-10-10 01:37
No problem and it's just Enabled I'm fairly certain.

**Comment by iHedgehog** [comment] 2015-10-10 03:38
@chroniX0 @theracermaster I confirm this. After changing xHCI to Enabled usb works well after sleep.

**Comment by theracermaster** [comment] 2015-10-10 21:32
Edited the wiki with the info by @chroniX0 (thanks!). Thanks for the confirmation as well @iHedgehog. Also tested it, is working well. Will close this issue for now.

**Closed by theracermaster** 2015-10-10 21:32 UTC
Labels: bug
